---
title: "predictionsmodel"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#TESTING PUSH

```

```{r}
test <- read_csv('https://raw.githubusercontent.com/randyhutton21/kagglepredictions/main/test.csv')
train <- read_csv('https://raw.githubusercontent.com/randyhutton21/kagglepredictions/main/train.csv')
head(train)
head(test)
```

```{r mutate datatypes}
train <- train %>%
  mutate_at(c('MSZoning', 'MSSubClass', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
              'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition','OverallQual', 'OverallCond', 
              'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 
              'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
              'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 
              'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
              'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition', 'GarageYrBlt', 'MoSold', 
              'YrSold'), ~as.factor(.))

test <- test %>%
  mutate_at(c('MSZoning', 'MSSubClass', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
              'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition','OverallQual', 'OverallCond', 
              'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 
              'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
              'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 
              'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
              'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition', 'GarageYrBlt', 'MoSold', 
              'YrSold'), ~as.factor(.))
```

```{r}
summary(train)
```

```{r establish correlations}
correlationsframe <- train %>%
  select_if(is.numeric)%>%
  na.omit()
correlationsframe
```

```{r create correlation plot}
library(corrplot)
correlations <- cor(na.omit(correlationsframe))
corrplot(correlations, method = "square")
```

```{r create general linear model}
model <- glm(SalePrice ~ GarageArea + GarageCars + Fireplaces + FullBath + GrLivArea + TotalBsmtSF + `1stFlrSF` + BsmtFinSF1, data = train)

pricepredictions <- predict(model, test)
```

```{r}
head(pricepredictions)
```

```{r}
test <- test %>%
  mutate(SalePrediction = pricepredictions)
```

```{r create final dataframe}
predictionsDF <- test %>%
  select(Id)%>%
  mutate(SalePrice = pricepredictions)
predictionsDF <- predictionsDF %>%
  mutate(SalePrice = ifelse(is.na(SalePrice), mean(SalePrice, na.rm = TRUE), SalePrice))
```

```{r}
predictionsDF %>%
  filter(is.na(SalePrice))
```

```{r write file}
write.csv(predictionsDF, file = 'HousingPricePredictionsVer1.csv', row.names = FALSE)
```

